### ISSUE TITLE
How to split post like WordPress <!--nextpage-->

### ISSUE THREAD

**Issue by kohki-shikata** [hexojs/hexo#3035] opened 2018-02-19 09:47 UTC
In WordPress, we can split post with the tag "&lt;!--nextpage--&gt;" in the post text, then output one post to consisted multiple pages like below...

http://example.com/permalink/?page=2
http://example.com/permalink/?page=3
http://example.com/permalink/?page=4
…
So, does anyone know how to same function in Hexo?

originalpost: https://groups.google.com/forum/#!topic/hexo/SH-QaSEEg4g

**Comment by tcrowe** [comment] 2018-02-19 23:01
Hi @kohki-shikata. That is an interesting question.

What about this?

```html
<a id="page-marker-01" style="page-break-after: always;"></a>
```

This attribute `id="page-marker-01"` allows a link to the page. Example: `http://example.com/my-blog#page-marker01`

The attribute `style="page-break-after: always;"` will *force a new page when printing.*

Will that work for your purposes?

**Comment by kohki-shikata** [comment] 2018-02-20 02:55
@tcrowe 
I aim to get google's search evaluation as multiple pages. But, This method works only for single HTML file.
Thanks your idea, but I would like to wait little more other ideas.

**Comment by tcrowe** [comment] 2018-02-20 03:19
Lets try another approach. Asset folders!

https://hexo.io/docs/asset-folders.html

`hexo new post my-post`

That will create a directory `source/_posts/my-post` AND a markdown file `source/_posts/my-post/index.md`.

More pages can be added in it:

`touch source/_posts/my-post/part02.md`
`touch source/_posts/my-post/part03.md`

Link to the pages:

```md
[Pg 1](./index.html) [Pg 2](./part02.html) [Pg3](./part03.html)
```

That may accomplish similar to what you want. I will check for a multi-page plugin now.

**Comment by tcrowe** [comment] 2018-02-20 03:30
I searched for "hexo plugin multiple page post" but I did not find anything yet. Are you good at JS? Can you make a plugin for this? It would be a good plugin to use with asset folders.

**Comment by stevenjoezhang** [comment] 2019-09-29 16:05
Duplicate of https://github.com/hexojs/hexo/issues/896

**Comment by stevenjoezhang** [comment] 2023-07-27 01:52
I will close this Issue because implementing this feature in Hexo is complex. If the input is a single Markdown file while generating multiple HTML outputs, it would require significant modifications to existing mechanisms (such as permalink and post asset), resulting in substantial maintenance costs.

I suggest implementing this through a frontend JS script within the theme. By using JS to analyze GET parameters and manipulate HTML, it can selectively display specific content on the page.

**Closed by stevenjoezhang** 2023-07-27 01:52 UTC
Labels: feature-request
