### ISSUE TITLE
repeated posts when  I edit the post !

### ISSUE THREAD

**Issue by iamhanson** [hexojs/hexo#849] opened 2014-09-19 09:05 UTC
###when I edit my post and save,there will be a lot of repeated posts in the list.for example.
when  I edit "hexo" and save ,then refresh my blog,there will be 3  same posts at least named  hexo".
![cut](https://cloud.githubusercontent.com/assets/3264635/4333071/40e98044-3fdc-11e4-8ab0-828768850396.png)

**Comment by szarouski** [comment] 2015-01-20 00:42
This is a duplicate of https://github.com/hexojs/hexo/issues/772, please close

**Closed** 2015-01-22 08:48 UTC
