### ISSUE TITLE
Feature request: add options argument to js helper

### ISSUE THREAD

**Issue by YoshinoriN** [hexojs/hexo#3426] opened 2019-01-23 08:44 UTC
## Proposal

I want to apply `async` [attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Attributes) to `<script>` tag using by [js-helper](https://hexo.io/docs/helpers#js)

**Comment by SukkaW** [comment] 2020-01-01 18:25
The issue is the subset of #3687 and is fixed in #3681. Newest version of Hexo already has this feature.

**Closed by SukkaW** 2020-01-01 18:25 UTC
Labels: feature-request
