### ISSUE TITLE
Improve the files considered by YAML grammar checker.

### ISSUE THREAD

**Issue by HoshinoTouko** [hexojs/hexo#4187] opened 2020-03-14 18:11 UTC
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

I have a problem after I add pace and pjax to my source/lib folder as a git submodule.

```bash
$ git submodule add https://github.com/theme-next/theme-next-pace source/lib/pace
```

After this, everytime I execute `hexo g` or `hexo s`, I will get a ERROR like this

```
YAMLException: end of the stream or a document separator is expected at line 9, column 102:
     ... languages` and other directories:
                                         ^
    at generateError (C:\Projects\Website\wasteland\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    ...
```

I found the wrong file. They are the README.md files of this two library, a colon without space after it.

![image](https://user-images.githubusercontent.com/13916411/76687718-8b1cc200-6661-11ea-93cd-d195cc06c7fb.png)

I have to add a exclude rule at `_config.yml` to fix this error.

```yaml
exclude: 
    - lib/**/*.md
```

It's a little unpleasant. I think the YAML format checker can be more clever to skip these unnecessary files to avoid unnecessary errors.

**Comment by SukkaW** [comment] 2020-03-15 03:19
Well, it is clear that the issue only occurs after your installing a `theme-next`'s plugin. Since I have no idea how `theme -next`'s plugins works, maybe @stevenjoezhang has better understanding of it.

I have noticed the plugin is setup inside `source` folders, which means any `*.md` files will be handled by hexo by default.

I believe the problem is about the theme and itd own plugin which is not related with Hexo, I am going to close this issue now.

**Comment by stevenjoezhang** [comment] 2020-03-15 09:13
I think Hexo needs to give proper warnings in the documentation of `skip_render`. Not only markdown files, javascript will also be processed by hexo filters. Sometimes this does not match the expected behavior of users.
Relevant issues: https://github.com/hexojs/hexo/issues/2522 https://github.com/hexojs/hexo/issues/1591

**Comment by SukkaW** [comment] 2020-03-16 03:31
> javascript will also be processed by hexo filters

IMHO it could caused by plugin developer which uses faulty type of filter.

**Comment by stevenjoezhang** [comment] 2020-03-16 04:36
Honestly,  I used to think that `after_post_render` would only be executed on posts with the `md` suffix, but Hexo's behavior is to apply this filter to almost all files in the source directory, including `js` and `css`. If the user does not set `skip_render` correctly, `js` and `css` files will be processed, and some Hexo plugins will make them malformed.
1. Hexo documentation should remind users to set `skip_render` correctly, or remind plugin developers that `after_post_render` will execute on both post and asset: https://github.com/hexojs/site/issues/581
2. Another solution is to disable some filters, such as `after_post_render`, for post / asset using plain renderer.
https://github.com/hexojs/hexo/blob/d83557855f2467abce6fd24768bf435379062681/lib/plugins/renderer/index.js#L8-L11
Developers are still able to modify js and css files with `after_render` filter:
https://github.com/hexojs/hexo-clean-css/blob/master/index.js#L9

https://hexo.io/api/filter#after-post-render
https://hexo.io/docs/configuration#Directory
https://github.com/MoePlayer/hexo-tag-aplayer/blob/d7175376bd505aab0d5350c5e6bcf64ca74c2478/index.es#L83

**Comment by stevenjoezhang** [comment] 2020-03-23 04:55
Another possible reason is that all the js and css files in the source folder are judged as pages
https://github.com/hexojs/hexo/blob/6437ff51869faf1add5cbb1f5411586b61a93fbf/lib/plugins/processor/asset.js#L118-L124

**Comment by stevenjoezhang** [comment] 2020-08-07 09:34
NexT provides a new way to manage plugins: https://github.com/next-theme/plugins

**Closed by stevenjoezhang** 2020-08-07 09:34 UTC
Labels: need-investigation, plugin, skip-render
