### ISSUE TITLE
When multiple lines of code are copied, the line numbers are copied together

### ISSUE THREAD

**Issue by Creling** [hexojs/hexo#3913] opened 2019-12-07 09:20 UTC
when I want to copy code across lines, the line numbers are copied as well, which is not what i expected.
![](https://ae01.alicdn.com/kf/Uafce4b80498a40638c09a2c8ee95dc3e5.png)

but it works well in previous versions.
![](https://ae01.alicdn.com/kf/U493c3d24d6c14b59ad8bc592c699e0726.png)

my hexo version is 4.0.0

I try to using a different rendering engine(marked and markdown-it), but the problem persists, so I guess this problem is caused by hexo itself.

**Comment by Creling** [comment] 2019-12-07 09:39
I did some research trying to find out why.
in previous versions, the block code is rendered like this:
![](https://ae01.alicdn.com/kf/H149457a187404d3fb63d2abd53962ee6V.jpg)
![](https://ae01.alicdn.com/kf/H7dec79bc2dfa4ba7b3c0823d6d93ad899.jpg)
So I can copy codes without line numbers easily.

but now, the block code is rendered like this:
![](https://ae01.alicdn.com/kf/Hfefac63d1b684ac8b3814047b613d3cfs.jpg)
![](https://ae01.alicdn.com/kf/H184f6ab5a31145508eba07644a9694ddp.jpg)
and I cannot copy codes without line numbers any more.

**Comment by stevenjoezhang** [comment] 2019-12-07 11:21
This is a bug of the theme you are using. The non-selectable elements are controlled by the theme's style sheet.

**Comment by Creling** [comment] 2019-12-07 11:31
> 
> 
> This is a bug of the theme you are using. The non-selectable elements are controlled by the theme's style sheet.

Even the default theme "landscape" has such a problem. May I know which theme you are using?

**Comment by stevenjoezhang** [comment] 2019-12-07 12:07
May I know which theme you are using?

**Comment by Creling** [comment] 2019-12-07 12:17
> 
> 
> May I know which theme you are using?

maupassant

**Comment by stevenjoezhang** [comment] 2019-12-07 13:14
> but it works well in previous versions.

![截屏2019-12-07下午9 02 02](https://user-images.githubusercontent.com/16272760/70375101-f1909680-1934-11ea-8148-30073dfdc848.png)

In fact, the theme author's website (generated using an old version of Hexo) also has this problem - the theme maupassant does not prohibit the selection of line numbers.
Some themes set `user-select: none` in the style sheet, which works under any Hexo version.

**Comment by Creling** [comment] 2019-12-07 13:24
> 
> 
> > but it works well in previous versions.
> 
> ![截屏2019-12-07下午9 02 02](https://user-images.githubusercontent.com/16272760/70375101-f1909680-1934-11ea-8148-30073dfdc848.png)
> 
> In fact, the theme author's website (generated using an old version of Hexo) also has this problem - the theme maupassant does not prohibit the selection of line numbers.
> Some themes set `user-select: none` in the style sheet, which works under any Hexo version.

yep, the theme maupassant does not prohibit the selection of line numbers. however, in old version of Hexo, you can choose whether to select the line number freely.
![](https://ae01.alicdn.com/kf/Hecc1b89ce19d4faf9be41f9c2f22d671v.gif)

but in Hexo@4.0, you cant.

**Comment by stevenjoezhang** [comment] 2019-12-07 13:32
So? I have argued that this has never been a feature of the theme. You were able to select it because you used this particular method. **It doesn't have any robustness, so it's not surprising that it failed in the new version.**

**Comment by Creling** [comment] 2019-12-07 13:44
I think this is due to a change in the way code boxes are rendered in the new version, as I mentioned above. https://github.com/hexojs/hexo/issues/3913#issuecomment-562834033

> It doesn't have any robustness
Whether or not to choose a line number should be decided by the user,  prohibit the selection of line numbers.may not be the best solution.

This change seems not to appear to be reflected in the change log, and many themes will be affected, including the default theme.

**Comment by stevenjoezhang** [comment] 2019-12-07 14:00
> Whether or not to choose a line number should be decided by the user, prohibit the selection of line numbers may not be the best solution.

IMHO, you misunderstand how Hexo and Hexo themes work. Hexo only generates HTML. As for whether you can choose the text on the page, it's completely determined the theme. "Should be decided by the user" This is a question you should ask the author of the theme, not here.

**Comment by Creling** [comment] 2019-12-07 14:09
> you misunderstand how Hexo and Hexo themes work

You may have misunderstood what I meant. From the beginning to the end, the core of my issue
is that **hexo@4.0 changed the way code blocks are rendered and may cause some problems.**

As for my last paragraph, because you mentioned "lack of robustness", I added some of my own opinions, that is not important, so I put it at the end.

**Comment by stevenjoezhang** [comment] 2019-12-07 14:23
> hexo@4.0 changed the way code blocks are rendered and **may cause some problems**

The theme you are using does not set the behavior of the code block when the user selects it through CSS or JS, which leads you to preconceive it as a feature and think it is causing problems.
My point is clear: "Make the code easy to select all" has never been a feature. In other words, the core of your issue is not reliable.

**Comment by Creling** [comment] 2019-12-08 08:28
**I dont want to argue over the feature or not feature, reliable or not reliable any more.**

I randomly selected three themes to show the impact of changing rendering methods on them.

## 1. hexo-theme-Daily
  - before
     ![图片](https://user-images.githubusercontent.com/43109504/70386640-4506f100-19d6-11ea-8893-43d5e15ccdfd.png)
 - now
    ![图片](https://user-images.githubusercontent.com/43109504/70386662-6e278180-19d6-11ea-8f81-5a1f7555d168.png)
Line spacing is significantly wider, horizontal lines appear, and it is ugly

## 2. hexo-theme-Daily
- before
![图片](https://user-images.githubusercontent.com/43109504/70386738-281eed80-19d7-11ea-9f7e-8ab6c231d84d.png)

- now
![图片](https://user-images.githubusercontent.com/43109504/70386718-06be0180-19d7-11ea-8dac-73e8b98942de.png)
emmmm ???
## 3. hexo-theme-Daily
![](https://ae01.alicdn.com/kf/Uaefff48892df49ecaa6a26f8af68deacf.gif)
cannot select code across lines anymore


**As for whether thoes are problems or not, Others will make judgments.**

**Comment by Creling** [comment] 2019-12-08 08:36
> Some themes set user-select: none in the style sheet, which works under any Hexo version.

Thanks for your help, I modified the theme manually. But I insist that changing rendering methods will cause a lot of unnecessary trouble

**Comment by stevenjoezhang** [comment] 2019-12-08 08:40
I will no longer waste time on this issue. For an open source project, some changes will inevitably occur when the version is updated. If you are unhappy with this, then you always have the right to choose not to update.
Also, I regret the lack of maintenance of these Hexo themes.

**Comment by SukkaW** [comment] 2019-12-09 15:04
Just as @stevenjoezhang said, the issue is ONLY RELATED TO YOUR THEME, not Hexo.

I am going to close this issue now since I believe @stevenjoezhang already explain the relationship between Hexo and its theme very clearly.

**Closed by SukkaW** 2019-12-09 15:04 UTC
