### ISSUE TITLE
deployments are slow

### ISSUE THREAD

**Issue by Lizhooh** [hexojs/hexo#2759] opened 2017-09-17 03:07 UTC
My blog 150+ article, which takes more than 10 minutes each deployment.
CPU has a high occupancy rate at deployment.
Are you the same?

commands that are used: `hexo clean && hexo d -g`

name | version 
--- | ---
nodejs | v8.2
hexo | v3.3.9

**Comment by tea3** [comment] 2017-09-18 03:01
The situation is somewhat similar, but my blog seems to be somewhat faster. The situation is similar. My blog 230+ article , which takes 6 minutes each deployment.

It may be different depending on the your plugin.

- hexo v3.3.9
- node.js v8.5

```
$ npm ls --depth 0
hexo-site@0.0.0 hexo
├── hexo@3.3.9
├── hexo-clean-css@0.0.3
├── hexo-deployer-git@0.3.1
├── hexo-deployer-netlify@0.0.4 (git+https://github.com/tea3/hexo-deployer-netlify.git#68f533757cd63987dd656811456e69add25e1a3b)
├── hexo-front-matter-excerpt@0.2.0
├── hexo-fs@0.2.2
├── hexo-generator-amp@3.0.5
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0 (git+https://github.com/tea3/hexo-generator-feed.git#6bf6f0fd5aefdca02e032cbe7581a214b881a658)
├── hexo-generator-index@0.2.0 (git+https://github.com/tea3/hexo-generator-index.git#74d86309af930849b41f60db98894031e130fd24)
├── hexo-generator-robotstxt@0.2.0
├── hexo-generator-search@1.0.2 (git+https://github.com/tea3/hexo-generator-search.git#d3f88cc2adabd43d429388c857d39f717ed2594e)
├── hexo-generator-seo-friendly-sitemap@0.0.21
├── hexo-generator-single-page@0.0.1 (git+https://git@github.com/dotimpact/hexo-generator-single-page.git#fb983a67e04193f624cb8ffa95b2fab75ec95196)
├── hexo-generator-tag@0.2.0 (git+https://github.com/tea3/hexo-generator-tag.git#946b712a81c4cb78bea151738cdb8eff1b8a5697)
├── hexo-html-minifier@0.0.2
├── hexo-include-markdown@1.0.2
├── hexo-related-popular-posts@2.0.2
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
├── hexo-tag-codepen@0.2.2
├── hexo-tag-flickr@0.3.3 (git+https://github.com/tea3/hexo-tag-flickr.git#a684dab69fcd44f5998049277075dd4d0b1ddae1)
├── hexo-tag-googlemaps@1.2.1
├── hexo-tag-instagram@1.0.3
├── hexo-tag-random-embed@0.0.1 (git+https://github.com/tea3/hexo-tag-random-embed.git#52542faa9e6760e3b1c651cdf8441117cf241f28)
├── hexo-tag-soundcloud@1.0.2
├── hexo-tag-twentytwenty@0.0.4
├── hexo-tag-twitter@1.0.1
├── hexo-toc@1.0.8 (git+https://github.com/tea3/hexo-toc.git#7c9624c2d3fb7d13ce973cb8de4dc10ff865c089)
├── hexo-uglify@0.0.4
├── iso8601@1.1.1
├── marked@0.3.6
├── minimatch@3.0.4
└── mkdirp@0.5.1
```

**Comment by Lizhooh** [comment] 2017-09-18 09:46
@tea3 

When deployed, opening other applications will take longer.

So, I have to wait until the deployment is complete before I do anything else.

My CPU i5-4300U 1.9GHz

**Comment by NoahDragon** [comment] 2017-09-18 21:36
I don't have that many articles. Is that okay to share your source codes?

**Comment by Lizhooh** [comment] 2017-09-19 11:27
@NoahDragon 
My blog is written in Chinese.
`Chinese character` need more CPU ?

My blog: http://me.lizhooh.com/

**Comment by NoahDragon** [comment] 2017-09-19 13:16
@Lizhooh Not really. I just wonder if I could have your all the source files under your hexo folder to investigate the issue. Right now, we know there is a performance issue in hexo, but don't have enough data to test with. Because the performance may be caused by different aspects, some caused by high volume of posts, some are incorrect implementation of the theme. Need to have the source code to take a look.

**Comment by Lizhooh** [comment] 2017-09-19 13:58
@NoahDragon 

Can I put my source codes through the mail to you, but you have to promise that it's for testing only.
If you agree, reply your email. Thank.

**Comment by NoahDragon** [comment] 2017-09-19 18:37
@Lizhooh thanks, you have my words, I will only use it for testing. You could send it to hi@abnerchou.me .

**Comment by Lizhooh** [comment] 2017-09-20 04:16
@NoahDragon Already sent

**Comment by JLHwung** [comment] 2017-10-22 00:07
Duplicate #2579.

**Comment by NoahDragon** [comment] 2017-10-27 14:27
@Lizhooh FYI. I could reproduce the issue, but don't have time to dig into.

**Comment by Lizhooh** [comment] 2017-10-28 11:38
@NoahDragon After I tried to remove [hexo-wordcount](https://github.com/willin/hexo-wordcount), the  build became faster.

**Comment by NoahDragon** [comment] 2017-10-30 14:13
@Lizhooh Thanks for the info. I take a look at the code on hexo-wordcount, it does cause the performance issue, and it doesn't provide the trace message.

I will close the issue for now. Please feel free to reopen it.

**Closed by NoahDragon** 2017-10-30 14:13 UTC
Labels: #perfmatters

**Comment by NoahDragon** [comment] 2017-11-16 16:44
The issue is caused by the html-to-text packages, it converts every html files into plain text, then count words based upon that. I have created an issue on hexo-wordcount, hope they could come up some solutions. https://github.com/willin/hexo-wordcount/issues/10

**Comment by Lizhooh** [comment] 2017-11-17 11:54
got it.

**Comment by ivan-nginx** [comment] 2018-01-01 14:08
[hexo-symbols-count-time](https://github.com/theme-next/hexo-symbols-count-time). No deps. Welcome.
