### ISSUE TITLE
hexo-cli无法安装成功，npm ERR! path /usr/local/node-8.9.1/lib/node_modules/hexo-cli/node_modules/highlight.js/tools/build.js

### ISSUE THREAD

**Issue by yh11971** [hexojs/hexo#3467] opened 2019-02-25 15:40 UTC
[root@centos7 /]# npm install -g hexo-cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! path /usr/local/node-8.9.1/lib/node_modules/hexo-cli/node_modules/highlight.js/tools/build.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/node-8.9.1/lib/node_modules/hexo-cli/node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-25T15_33_05_969Z-debug.log

**Comment by 1296mhz** [comment] 2019-02-25 16:17
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
/etc/os-release (END)

# node -v
v10.15.1

# npm install -g hexo-cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! path /usr/lib/node_modules/hexo-cli/node_modules/highlight.js/tools/build.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/hexo-cli/node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-25T16_17_15_386Z-debug.log

**Comment by jowi24** [comment] 2019-02-25 18:10
Same happens with `docker run -it node:latest npm install hexo-cli -g`

**Comment by jodumont** [comment] 2019-02-25 20:22
duplicate of #3466

**Comment by chocoluffy** [comment] 2019-02-25 20:52
It works for me by having: `npm install -g hexo-cli --ignore-scripts`, to ensure that npm download those packages but does not build them. It's a temporary workaround as the dependency issue on `highlight.js` should be fixed soon.

**Comment by chocoluffy** [comment] 2019-02-25 22:14
(Option 1)
`npm install -g hexo-cli --ignore-scripts` can help, as it simply download the packages without building it, thus it will avoid the error caused by dep package like here in `highlight.js`. But use it with caution, as it may cause other useful packages to stop building as well. 

(Option 2)
I recommend install packages from your `npm-shrinkwrap.json` file instead of directly installing latest `hexo-cli`, as this package is currently affected by its deps `highlight.js` and waiting for fix.

So do `npm shrinkwrap` to generate above json file, and then `npm install` will install packages from shrinkwrap locked version, such that you are installing from a known working version, rather the latest one.

I encounter the same problem as title on Travis when deploying my hexo blog, and the above-mentioned tricks help solve the error.

**Comment by tomap** [comment] 2019-02-26 05:18
Duplicate of #3466

**Closed by tomap** 2019-02-26 05:18 UTC
