### ISSUE TITLE
Pages服务部署，

### ISSUE THREAD

**Issue by xiaomo314** [hexojs/hexo#3731] opened 2019-09-25 01:06 UTC
部署在coding上，之前好好着，突然就部署失败，日志这样的，请教一下
2019/09/25 08:51:21 Fetching depot archive:
	Ref: refs/heads/master
	CommitSHA: 04849744256d5a1f3a7ac918898f7e4bf8523855
2019/09/25 08:51:21 Fail to fetch archive.

**Comment by WitherZuo** [comment] 2019-09-25 01:21
这应该是Coding Pages服务的问题，建议向Coding的客服咨询相关情况。

**Comment by YoshinoriN** [comment] 2019-09-26 10:11
@xiaomo314
As @WitherZuo say this problem not caused by hexo. I close this issue.

@WitherZuo 
Thank you for your support :)

**Closed by YoshinoriN** 2019-09-26 10:11 UTC
Labels: question
