### ISSUE TITLE
hexo init,but no file created

### ISSUE THREAD

**Issue by lucoxlee** [hexojs/hexo#2646] opened 2017-07-11 07:03 UTC
## it shows:

`root@ubuntu:/home/soft# hexo init blog

INFO  Cloning hexo-starter to /home/soft/blog
WARN  git clone failed. Copying data instead
WARN  Failed to install dependencies. Please run 'npm install' manually!
`

**Comment by TopVitamin** [comment] 2017-07-11 09:15
first: 'npm install' then will be ok

**Comment by NoahDragon** [comment] 2017-07-11 14:18
As @TopVitamin mentioned, run `npm install` instead.

**Comment by lucoxlee** [comment] 2017-07-12 02:24
thanks, but you mean run `npm install ` ahead, I got this 
![1](https://user-images.githubusercontent.com/16668518/28098972-076446bc-66ec-11e7-9f62-326ddac458e9.jpg)
what should I do

**Comment by tea3** [comment] 2017-07-12 06:38
@lucoxlee 
It is recommended to delete all the folders and try again.
Can you solve this issue as follow ?

```
# cd ~/soft
# ls
# rm -rf blog
# hexo init blog
# cd blog
# ls
# npm install
# hexo s
```

**Comment by lucoxlee** [comment] 2017-07-12 11:56
thanks, it's not solved, it shows:
![1](https://user-images.githubusercontent.com/16668518/28116561-2525d01c-673c-11e7-9b54-c9e1c5a1ee60.jpg)

**Comment by NoahDragon** [comment] 2017-07-12 14:23
@lucoxlee Could you please try to clone the repo https://github.com/hexojs/hexo-starter , then run `npm install` inside the folder?

**Comment by lucoxlee** [comment] 2017-07-16 05:52
thanks, well, another server hasn't this problem

**Comment by connor11528** [comment] 2017-08-16 16:04
@lucoxlee can we close this issue out?

**Closed** 2017-08-18 07:09 UTC

**Comment by ratoi-crysty** [comment] 2017-10-27 07:30
I know this has already been closed but I just want to add a small info for future users that stumble on this. This can also be caused by not having GIT installed on your PC.

**Comment by JeHwanYoo** [comment] 2019-09-24 11:48
let's try to type `sudo hexo init blog`

**Comment by imleoo** [comment] 2019-10-23 06:42
did you not install git in your PC?  I have this error too ,but before install git ,it's ok.

**Comment by lonely-island** [comment] 2020-03-22 09:39
> I know this has already been closed but I just want to add a small info for future users that stumble on this. This can also be caused by not having GIT installed on your PC.

thanks XD,it really helpful, i try to migrate my blog from wordpress on ECS to hexo, but forget didn't install git first , headache for a while
