### ISSUE TITLE
Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency

### ISSUE THREAD

**Issue by g199209** [hexojs/hexo#4619] opened 2021-01-22 10:26 UTC
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

`hexo g` works fine, without any warning. But when I try `hexo s` and open the browser, there are some warnings: 

```
~ hexo s

INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
(node:60268) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60268) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:60268) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:60268) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:60268) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:60268) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
^CINFO  Good bye
```

Run hexo using `node --trace-warnings`:

```
~ node --trace-warnings /usr/local/bin/hexo s
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
(node:59880) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:698:11)
    at Object.get (node:internal/modules/cjs/loader:712:5)
    at Boolean.Node [as constructor] (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/node.js:42:23)
    at new Boolean (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/lexer.js:13:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/parser.js:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
(node:59880) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:698:11)
    at Object.get (node:internal/modules/cjs/loader:712:5)
    at Boolean.Node [as constructor] (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/node.js:43:23)
    at new Boolean (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/lexer.js:13:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/parser.js:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
(node:59880) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:698:11)
    at Object.get (node:internal/modules/cjs/loader:712:5)
    at Boolean.Node [as constructor] (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/node.js:44:25)
    at new Boolean (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/lexer.js:13:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/parser.js:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
(node:59880) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:698:11)
    at Object.get (node:internal/modules/cjs/loader:712:5)
    at Boolean.Node [as constructor] (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/node.js:42:23)
    at new Boolean (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/lexer.js:13:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/parser.js:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
(node:59880) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:698:11)
    at Object.get (node:internal/modules/cjs/loader:712:5)
    at Boolean.Node [as constructor] (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/node.js:43:23)
    at new Boolean (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/lexer.js:13:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/parser.js:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
(node:59880) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:698:11)
    at Object.get (node:internal/modules/cjs/loader:712:5)
    at Boolean.Node [as constructor] (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/node.js:44:25)
    at new Boolean (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/lexer.js:13:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gaomingfei/Blog/node_modules/nib/node_modules/stylus/lib/parser.js:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
^CINFO  Catch you later
```

I found  issue #4257, these two problem look like the same problem, causing by stylus. 

This problem still exist in newest version of hexo and node.js.

## Environment & Settings

**Node.js & npm version**

```
Node: v15.5.1
npm: 7.3.0
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo: 5.3.0
hexo-cli: 3.1.0
os: Darwin 19.6.0 darwin x64
node: 15.5.1
v8: 8.6.395.17-node.23
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 88
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1i
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0


hexo-site@0.0.0 /Users/gaomingfei/Blog
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-search@2.4.1
├── hexo-generator-sitemap@2.1.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.3.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
└── hexo@5.3.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.3.0"
  },
  "dependencies": {
    "hexo": "^5.3.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-search": "^2.4.1",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.3.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^2.0.0"
  }
}%
```

**Comment by stevenjoezhang** [comment] 2021-01-24 12:03
Closed as it duplicates https://github.com/hexojs/hexo/issues/4257
Please search for existing issues before creating a new issue, thanks.

**Closed by stevenjoezhang** 2021-01-24 12:03 UTC

**Comment by g199209** [comment] 2021-01-25 03:05
@stevenjoezhang  I have checked #4257, but that issue is about node 14, but in this issue, I use node 15.

And from that issue, it seems this problem has been solved. But this problem still exist in leatest version of Hexo and Node.

**Comment by stevenjoezhang** [comment] 2021-01-25 06:57
> that issue is about node 14, but in this issue, I use node 15.

The same error message will be reproduced in every node.js version after [this commit](https://github.com/nodejs/node/commit/d7452b7140929835f4032099106fc9d14e668210) 

> And from that issue, it seems this problem has been solved. But this problem still exist in leatest version of Hexo and Node.

It has been solved in the master branch, but a new version of `stylus/nib` is not released so this problem still exist. See https://github.com/stylus/nib/pull/348

**Comment by g199209** [comment] 2021-01-26 03:00
Thanks！

**Comment by tjx666** [comment] 2021-11-22 18:57
@stevenjoezhang Still facing this issue in node 16.3.0
![image](https://user-images.githubusercontent.com/41773861/142919337-4a87f5b0-6db7-4834-8c33-a2fe4bef9e99.png)

Vesion info:

```
  "dependencies": {
    "hexo": "^5.4.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-searchdb": "^1.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.1.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^2.0.0"
  },
  "devDependencies": {
    "hexo-admin": "^2.3.0",
    "hexo-deployer-git": "^3.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-yam": "^6.0.0",
    "husky": "^4.3.8",
    "prettier": "^2.4.1",
    "pretty-quick": "^3.1.2"
  }
```

**Comment by tjx666** [comment] 2021-11-22 19:01
![image](https://user-images.githubusercontent.com/41773861/142919838-b618d901-b725-4634-810e-a5fd9d745fec.png)

**Comment by stevenjoezhang** [comment] 2021-11-23 08:06
We are not able to resolve the issue, unless a new version of nib is released: https://github.com/stylus/nib/pull/350
I am sorry that this problem has confused Hexo developers and users for over one year. The update of stylus and nib is very slow, but due to historical reasons we cannot drop this dependency
