### ISSUE TITLE
Permalink issues

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1813] opened 2016-03-07 05:35 UTC
This is an umbrella issue pertaining permalink in Hexo.
We should document how permalink (or link in general) is resolved from `config.permalink`, `post.permalink` file name, slug, title.
These cause quite a bit of confusion for the users and escaping of special characters.
#1812
#1608
#1110
#881 / #1258

https://github.com/hexojs/hexo-generator-sitemap/issues/1 Use URL safe characters (slug should be serving this purpose)
https://github.com/hexojs/hexo-generator-sitemap/issues/13 Use permalink as canonical URL (in HTML header and sitemap)
#1822 `.` in post file name

**Comment by leesei** [comment] 2016-03-15 15:14
From #1822, I recommend issuing a warning for posts and assets with non-URL safe characters (`slugtize(filename) !== filename`).
We can inform users to use `post.permalink` instead.

**Comment by Ether0xF** [comment] 2016-07-12 09:54
I see this is an umbrella issue, so I decide to append the issue here as discussion instead of posting a new (and duplicated) one.
The permalink overriding bug, refers to #1110 and #1158, was still happening in my hexo project as hexo version 3.2.2.
In config.yml, my permalink is:
```
permalink: :category/:year-:month-:day/
```
In front-matter, I set the permalink like:
```
permalink : /title-I-want/
```
but it did not override the permalink in config.yml.
I'm wondering that if I set the value in an appropriate format. What exactly the format is?

Solution provided by @liudongkai was not a handy one that I expected, since I have 180+ posts that migrated from wordpress. Re-assign a permalink to each post manually sounds incredible...
Any other suggestions would be very appreciated.

**Comment by curbengh** [comment] 2019-08-30 09:16
> In front-matter, I set the permalink like:
> 
> ```
> permalink : /title-I-want/
> ```
> 
> but it did not override the permalink in config.yml.

what if you set `permalink: :title/`?

**Comment by icpz** [comment] 2020-03-02 17:25
Any updates? Seems that the issue is still there in hexo 3.8

**Comment by stevenjoezhang** [comment] 2020-06-14 02:34
There is a discussion about it: #3464
I'm closing this issue. Please join the discussion there :)

**Closed by stevenjoezhang** 2020-06-14 02:34 UTC
Labels: bug, discussion, question
