### ISSUE TITLE
asciidoctor.js won't run with Hexo

### ISSUE THREAD

**Issue by loki2302** [hexojs/hexo#1728] opened 2016-01-26 20:23 UTC
Originally here: hcoona/hexo-renderer-asciidoc#3 - this issue is a blocker for hexo-renderer-asciidoc plugin.

`asciidoctor.js` fails to initialize when loaded in Hexo context. Minimal steps to reproduce:
1. Generate a minimal Hexo blog with `hexo init`
2. `npm install --save asciidoctor.js`
3. `mkdir scripts`
4. Put `dummy.js` into `scripts` with content `require('asciidoctor.js')();` (this exact one line)
5. Run `hexo generate`

The error message will appear:

```
/home/loki2302/hexo-experiment/blog1/node_modules/JSONStream/index.js:91
      this.stack[k].value = null
                          ^

TypeError: Cannot assign to read only property 'value' of true
    at Parser.parser.onValue (/home/loki2302/hexo-experiment/blog1/node_modules/JSONStream/index.js:91:27)
    at Parser.proto.emit (/home/loki2302/hexo-experiment/blog1/node_modules/jsonparse/jsonparse.js:265:8)
    at Parser.proto.onToken (/home/loki2302/hexo-experiment/blog1/node_modules/jsonparse/jsonparse.js:276:12)
    at Parser.parser.onToken (/home/loki2302/hexo-experiment/blog1/node_modules/JSONStream/index.js:96:12)
    at Parser.proto.write (/home/loki2302/hexo-experiment/blog1/node_modules/jsonparse/jsonparse.js:202:20)
    at Stream.<anonymous> (/home/loki2302/hexo-experiment/blog1/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/home/loki2302/hexo-experiment/blog1/node_modules/through/index.js:26:11)
    at ReadStream.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1822:12)
    at callback (/home/loki2302/hexo-experiment/blog1/node_modules/nunjucks/node_modules/graceful-fs/polyfills.js:207:17)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

My environment details:

```
loki2302@ubuntu:~/hexo-experiment/blog1$ hexo version
hexo: 3.1.1
os: Linux 3.19.0-47-generic linux x64
http_parser: 2.5.0
node: 5.0.0
v8: 4.6.85.28
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2d
```

**Comment by hcoona** [comment] 2016-01-27 03:03
Can reproduce it.

More details with debug option.

```
10:52:49.950 DEBUG Hexo version: 3.1.1
10:52:49.950 DEBUG Working directory: R:\ad\
10:52:50.074 DEBUG Config loaded: R:\ad\_config.yml
10:52:50.265 DEBUG Script loaded: scripts\dummy.js
10:52:50.280 DEBUG Script loaded: themes\landscape\scripts\fancybox.js
10:52:50.296 DEBUG Plugin loaded: hexo-generator-category
10:52:50.296 DEBUG Plugin loaded: hexo-generator-archive
10:52:50.452 DEBUG Plugin loaded: hexo-renderer-stylus
10:52:50.452 DEBUG Plugin loaded: hexo-generator-index
10:52:50.468 DEBUG Plugin loaded: hexo-generator-tag
10:52:50.468 DEBUG Plugin loaded: hexo-renderer-ejs
10:52:50.593 DEBUG Plugin loaded: hexo-server
10:52:50.665 DEBUG Plugin loaded: hexo-renderer-marked
10:52:50.665 DEBUG Loading database.
R:\ad\node_modules\JSONStream\index.js:91
      this.stack[k].value = null
                          ^

TypeError: Cannot assign to read only property 'value' of true
    at Parser.parser.onValue (R:\ad\node_modules\JSONStream\index.js:91:27)
    at Parser.proto.emit (R:\ad\node_modules\jsonparse\jsonparse.js:265:8)
    at Parser.proto.onToken (R:\ad\node_modules\jsonparse\jsonparse.js:276:12)
    at Parser.parser.onToken (R:\ad\node_modules\JSONStream\index.js:96:12)
    at Parser.proto.write (R:\ad\node_modules\jsonparse\jsonparse.js:202:20)
    at Stream.<anonymous> (R:\ad\node_modules\JSONStream\index.js:23:12)
    at Stream.stream.write (R:\ad\node_modules\through\index.js:26:11)
    at ReadStream.ondata (_stream_readable.js:529:20)
    at emitOne (events.js:90:13)
    at ReadStream.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at onread (fs.js:1822:12)
    at callback (R:\ad\node_modules\nunjucks\node_modules\graceful-fs\polyfills.js:207:17)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

Env:

```
hexo: 3.1.1
os: Windows_NT 10.0.10586 win32 x64
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
```

**Comment by hcoona** [comment] 2016-01-27 03:06
https://github.com/hcoona/hexo-renderer-asciidoc/issues/3 mentioned that node v4 can also reproduce this issue.

**Comment by hcoona** [comment] 2017-11-26 09:20
It's OK to close it because I updated hexo-renderer-asciidoc to solve it.

**Closed** 2017-11-26 09:22 UTC
Labels: wontfix
