### ISSUE TITLE
inject.preload.js:373 causing errors while loading page

### ISSUE THREAD

**Issue by cassidydotdk** [hexojs/hexo#3209] opened 2018-07-12 16:25 UTC
## Environment Info

Node version(`node -v`): v8.2.1

Hexo and Plugin version(`npm ls --depth 0`): 

```
+-- hexo@3.3.8
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2
```

## For BUG

I have a near vanilla installation of Hexo using theme Icarus. When loading up the front page of the site, Chrome reports the following error:

![image](https://user-images.githubusercontent.com/8483909/42646190-6d86b950-8600-11e8-8e25-662297ecd670.png)

Output from `hexo server --debug`

```
16:22:03.590 DEBUG Hexo version: 3.3.8
16:22:03.593 DEBUG Working directory: [redacted]\cassidydotdk.github.io\
16:22:03.717 DEBUG Config loaded: [redacted]\cassidydotdk.github.io\_config.yml
16:22:03.731 DEBUG Script loaded: themes\icarus\scripts\meta.js
16:22:03.731 DEBUG Script loaded: themes\icarus\scripts\thumbnail.js
16:22:03.742 DEBUG Plugin loaded: hexo-deployer-git
16:22:03.746 DEBUG Plugin loaded: hexo-generator-feed
16:22:03.749 DEBUG Plugin loaded: hexo-generator-index
16:22:03.752 DEBUG Plugin loaded: hexo-generator-category
16:22:03.756 DEBUG Plugin loaded: hexo-renderer-ejs
16:22:03.757 DEBUG Plugin loaded: hexo-generator-tag
16:22:03.760 DEBUG Plugin loaded: hexo-generator-archive
16:22:03.762 DEBUG Plugin loaded: hexo-renderer-stylus
16:22:03.768 DEBUG Plugin loaded: hexo-renderer-marked
16:22:03.858 DEBUG Plugin loaded: hexo-server
16:22:03.865 DEBUG Loading database.
16:22:03.872 INFO  Start processing
16:22:03.893 DEBUG Processed: CNAME
16:22:03.933 DEBUG Processed: images/logo-400x400.png
16:22:03.935 DEBUG Processed: images/logo-64x64.png
16:22:03.977 DEBUG Theme config loaded.
16:22:03.978 DEBUG Processed: _config.yml
16:22:03.979 DEBUG Processed: images/mark-cassidy-circle.png
16:22:03.987 DEBUG Processed: source/css/style.styl
16:22:03.987 DEBUG Processed: source/js/insight.js
16:22:03.988 DEBUG Processed: source/js/main.js
16:22:04.018 DEBUG Processed: layout/archive.ejs
16:22:04.019 DEBUG Processed: layout/categories.ejs
16:22:04.019 DEBUG Processed: layout/index.ejs
16:22:04.020 DEBUG Processed: layout/category.ejs
16:22:04.020 DEBUG Processed: layout/page.ejs
16:22:04.020 DEBUG Processed: layout/layout.ejs
16:22:04.021 DEBUG Processed: layout/post.ejs
16:22:04.021 DEBUG Processed: layout/tag.ejs
16:22:04.022 DEBUG Processed: layout/tags.ejs
16:22:04.033 DEBUG Processed: about/index.md
16:22:04.034 DEBUG Processed: languages/es.yml
16:22:04.034 DEBUG Processed: languages/en.yml
16:22:04.035 DEBUG Processed: languages/fr.yml
16:22:04.035 DEBUG Processed: languages/ko.yml
16:22:04.035 DEBUG Processed: languages/ja.yml
16:22:04.036 DEBUG Processed: languages/pt-BR.yml
16:22:04.036 DEBUG Processed: languages/ru.yml
16:22:04.037 DEBUG Processed: languages/id.yml
16:22:04.037 DEBUG Processed: languages/tr.yml
16:22:04.038 DEBUG Processed: languages/zh-CN.yml
16:22:04.038 DEBUG Processed: languages/zh-TW.yml
16:22:04.039 DEBUG Processed: tags/index.md
16:22:04.039 DEBUG Processed: categories/index.md
16:22:04.054 DEBUG Processed: source/css/images/avatar.png
16:22:04.055 DEBUG Processed: source/css/images/logo-400x400.png
16:22:04.056 DEBUG Processed: source/css/images/logo-64x64.png
16:22:04.056 DEBUG Processed: source/css/images/logo.png
16:22:04.057 DEBUG Processed: source/css/images/thumb-default-small.png
16:22:04.057 DEBUG Processed: source/libs/justified-gallery/justifiedGallery.min.css
16:22:04.058 DEBUG Processed: source/libs/justified-gallery/jquery.justifiedGallery.min.js
16:22:04.058 DEBUG Processed: source/libs/open-sans/styles.css
16:22:04.060 DEBUG Processed: source/libs/source-code-pro/styles.css
16:22:04.066 DEBUG Processed: _posts/hello-world.md
16:22:04.083 DEBUG Processed: layout/comment/changyan.ejs
16:22:04.084 DEBUG Processed: layout/comment/disqus.ejs
16:22:04.085 DEBUG Processed: layout/comment/counter.ejs
16:22:04.086 DEBUG Processed: layout/comment/duoshuo.ejs
16:22:04.086 DEBUG Processed: layout/comment/facebook.ejs
16:22:04.086 DEBUG Processed: layout/comment/gitment.ejs
16:22:04.087 DEBUG Processed: layout/comment/index.ejs
16:22:04.087 DEBUG Processed: layout/comment/isso.ejs
16:22:04.088 DEBUG Processed: layout/comment/scripts.ejs
16:22:04.088 DEBUG Processed: layout/comment/livere.ejs
16:22:04.088 DEBUG Processed: layout/comment/youyan.ejs
16:22:04.089 DEBUG Processed: layout/comment/valine.ejs
16:22:04.089 DEBUG Processed: layout/common/article.ejs
16:22:04.090 DEBUG Processed: layout/common/head.ejs
16:22:04.090 DEBUG Processed: layout/common/footer.ejs
16:22:04.090 DEBUG Processed: layout/common/header.ejs
16:22:04.091 DEBUG Processed: layout/common/profile.ejs
16:22:04.091 DEBUG Processed: layout/common/scripts.ejs
16:22:04.091 DEBUG Processed: layout/common/sidebar.ejs
16:22:04.092 DEBUG Processed: layout/common/thumbnail.ejs
16:22:04.092 DEBUG Processed: layout/common/timeline.ejs
16:22:04.092 DEBUG Processed: layout/plugin/google-analytics.ejs
16:22:04.093 DEBUG Processed: layout/plugin/scripts.ejs
16:22:04.095 DEBUG Processed: layout/plugin/baidu-analytics.ejs
16:22:04.095 DEBUG Processed: layout/search/baidu.ejs
16:22:04.095 DEBUG Processed: layout/search/index-mobile.ejs
16:22:04.096 DEBUG Processed: layout/search/index.ejs
16:22:04.096 DEBUG Processed: layout/search/insight.ejs
16:22:04.097 DEBUG Processed: layout/share/addtoany.ejs
16:22:04.097 DEBUG Processed: layout/search/swiftype.ejs
16:22:04.097 DEBUG Processed: layout/share/bdshare.ejs
16:22:04.098 DEBUG Processed: layout/share/index.ejs
16:22:04.098 DEBUG Processed: layout/share/default.ejs
16:22:04.098 DEBUG Processed: layout/share/jiathis.ejs
16:22:04.099 DEBUG Processed: layout/widget/archive.ejs
16:22:04.099 DEBUG Processed: layout/widget/category.ejs
16:22:04.099 DEBUG Processed: layout/widget/links.ejs
16:22:04.100 DEBUG Processed: layout/widget/recent_posts.ejs
16:22:04.100 DEBUG Processed: layout/widget/tag.ejs
16:22:04.101 DEBUG Processed: layout/widget/tagcloud.ejs
16:22:04.102 DEBUG Processed: source/css/images/mark-cassidy-circle.png
16:22:04.102 DEBUG Processed: source/libs/font-awesome5/css/fa-brands.css
16:22:04.103 DEBUG Processed: source/libs/font-awesome5/css/fa-brands.min.css
16:22:04.105 DEBUG Processed: source/libs/font-awesome5/css/fa-solid.css
16:22:04.105 DEBUG Processed: source/libs/font-awesome5/css/fa-solid.min.css
16:22:04.106 DEBUG Processed: source/libs/font-awesome5/css/fontawesome.css
16:22:04.106 DEBUG Processed: source/libs/font-awesome5/css/fontawesome.min.css
16:22:04.107 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-brands-400.woff2
16:22:04.107 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-solid-900.woff
16:22:04.108 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-solid-900.woff2
16:22:04.108 DEBUG Processed: source/libs/lightgallery/css/lg-fb-comment-box.css
16:22:04.109 DEBUG Processed: source/libs/lightgallery/css/lg-fb-comment-box.css.map
16:22:04.110 DEBUG Processed: source/libs/lightgallery/css/lg-fb-comment-box.min.css
16:22:04.111 DEBUG Processed: source/libs/lightgallery/css/lg-transitions.css
16:22:04.112 DEBUG Processed: source/libs/lightgallery/css/lg-transitions.css.map
16:22:04.112 DEBUG Processed: source/libs/lightgallery/css/lg-transitions.min.css
16:22:04.113 DEBUG Processed: source/libs/lightgallery/css/lightgallery.css
16:22:04.114 DEBUG Processed: source/libs/lightgallery/css/lightgallery.css.map
16:22:04.115 DEBUG Processed: source/libs/lightgallery/css/lightgallery.min.css
16:22:04.115 DEBUG Processed: source/libs/lightgallery/fonts/lg.eot
16:22:04.116 DEBUG Processed: source/libs/lightgallery/fonts/lg.svg
16:22:04.116 DEBUG Processed: source/libs/lightgallery/fonts/lg.ttf
16:22:04.117 DEBUG Processed: source/libs/lightgallery/fonts/lg.woff
16:22:04.117 DEBUG Processed: source/libs/lightgallery/img/loading.gif
16:22:04.118 DEBUG Processed: source/libs/lightgallery/img/video-play.png
16:22:04.118 DEBUG Processed: source/libs/lightgallery/img/vimeo-play.png
16:22:04.119 DEBUG Processed: source/libs/lightgallery/img/youtube-play.png
16:22:04.119 DEBUG Processed: source/libs/lightgallery/js/lg-autoplay.js
16:22:04.119 DEBUG Processed: source/libs/lightgallery/js/lg-autoplay.min.js
16:22:04.120 DEBUG Processed: source/libs/lightgallery/js/lg-fullscreen.js
16:22:04.121 DEBUG Processed: source/libs/lightgallery/js/lg-fullscreen.min.js
16:22:04.121 DEBUG Processed: source/libs/lightgallery/js/lg-hash.js
16:22:04.122 DEBUG Processed: source/libs/lightgallery/js/lg-hash.min.js
16:22:04.122 DEBUG Processed: source/libs/lightgallery/js/lg-pager.js
16:22:04.123 DEBUG Processed: source/libs/lightgallery/js/lg-pager.min.js
16:22:04.125 DEBUG Processed: source/libs/lightgallery/js/lg-share.js
16:22:04.125 DEBUG Processed: source/libs/lightgallery/js/lg-thumbnail.js
16:22:04.126 DEBUG Processed: source/libs/lightgallery/js/lg-share.min.js
16:22:04.126 DEBUG Processed: source/libs/lightgallery/js/lg-thumbnail.min.js
16:22:04.127 DEBUG Processed: source/libs/lightgallery/js/lg-video.js
16:22:04.127 DEBUG Processed: source/libs/lightgallery/js/lg-video.min.js
16:22:04.128 DEBUG Processed: source/libs/lightgallery/js/lg-zoom.js
16:22:04.128 DEBUG Processed: source/libs/lightgallery/js/lg-zoom.min.js
16:22:04.129 DEBUG Processed: source/libs/lightgallery/js/lightgallery.js
16:22:04.130 DEBUG Processed: source/libs/open-sans/fonts/59ZRklaO5bWGqF5A9baEERJtnKITppOI_IvcXXDNrsc.woff2
16:22:04.130 DEBUG Processed: source/libs/lightgallery/js/lightgallery.min.js
16:22:04.131 DEBUG Processed: source/libs/open-sans/fonts/K88pR3goAWT7BTt32Z01mxJtnKITppOI_IvcXXDNrsc.woff2
16:22:04.140 DEBUG Processed: source/libs/open-sans/fonts/LWCjsQkB6EMdfHrEVqA1KRJtnKITppOI_IvcXXDNrsc.woff2
16:22:04.141 DEBUG Processed: source/libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNShWV49_lSm1NYrwo-zkhivY.woff2
16:22:04.142 DEBUG Processed: source/libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSj0LW-43aMEzIO6XUTLjad8.woff2
16:22:04.143 DEBUG Processed: source/libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSpX5f-9o1vgP2EXwfjgl7AY.woff2
16:22:04.144 DEBUG Processed: source/libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSq-j2U0lmluP9RWlSytm3ho.woff2
16:22:04.144 DEBUG Processed: source/libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSqaRobkAwv3vxw3jMhVENGA.woff2
16:22:04.145 DEBUG Processed: source/libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSugdm0LZdjqr5-oayXSOefg.woff2
16:22:04.145 DEBUG Processed: source/libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSv8zf_FOSsgRmwsS7Aa9k2w.woff2
16:22:04.146 DEBUG Processed: source/libs/open-sans/fonts/RjgO7rYTmqiVp7vzi-Q5URJtnKITppOI_IvcXXDNrsc.woff2
16:22:04.146 DEBUG Processed: source/libs/open-sans/fonts/cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw.woff2
16:22:04.147 DEBUG Processed: source/libs/open-sans/fonts/u-WUoqrET9fUeobQW7jkRRJtnKITppOI_IvcXXDNrsc.woff2
16:22:04.147 DEBUG Processed: source/libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBiYE0-AqJ3nfInTTiDXDjU4.woff2
16:22:04.148 DEBUG Processed: source/libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBjTOQ_MqJVwkKsUn0wKzc2I.woff2
16:22:04.148 DEBUG Processed: source/libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBjUj_cnvWIuuBMVgbX098Mw.woff2
16:22:04.149 DEBUG Processed: source/libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBkbcKLIaa1LC45dFaAfauRA.woff2
16:22:04.149 DEBUG Processed: source/libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBmo_sUJ8uO4YLWRInS22T3Y.woff2
16:22:04.150 DEBUG Processed: source/libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBo4P5ICox8Kq3LLUNMylGO4.woff2
16:22:04.150 DEBUG Processed: source/libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBr6up8jxqWt8HVA3mDhkV_0.woff2
16:22:04.151 DEBUG Processed: source/libs/open-sans/fonts/xozscpT2726on7jbcb_pAhJtnKITppOI_IvcXXDNrsc.woff2
16:22:04.151 DEBUG Processed: source/libs/source-code-pro/fonts/mrl8jkM18OlOQN8JLgasD9V_2ngZ8dMf8fLgjYEouxg.woff2
16:22:04.151 DEBUG Processed: source/libs/source-code-pro/fonts/mrl8jkM18OlOQN8JLgasDy2Q8seG17bfDXYR_jUsrzg.woff2
16:22:04.170 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-brands-400.eot
16:22:04.171 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-brands-400.ttf
16:22:04.171 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-brands-400.woff
16:22:04.172 DEBUG Processed: source/libs/jquery/2.1.3/jquery.min.js
16:22:04.174 DEBUG Processed: layout/common/post/category.ejs
16:22:04.175 DEBUG Processed: layout/common/post/banner.ejs
16:22:04.175 DEBUG Processed: layout/common/post/date.ejs
16:22:04.175 DEBUG Processed: layout/common/post/tag.ejs
16:22:04.176 DEBUG Processed: layout/common/post/gallery.ejs
16:22:04.176 DEBUG Processed: layout/common/post/nav.ejs
16:22:04.176 DEBUG Processed: layout/common/post/title.ejs
16:22:04.177 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-solid-900.eot
16:22:04.178 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-solid-900.ttf
16:22:04.180 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-solid-900.svg
16:22:04.182 DEBUG Processed: source/libs/font-awesome5/webfonts/fa-brands-400.svg
16:22:04.456 DEBUG Generator: page
16:22:04.457 DEBUG Generator: post
16:22:04.457 DEBUG Generator: feed
16:22:04.458 DEBUG Generator: index
16:22:04.458 DEBUG Generator: category
16:22:04.458 DEBUG Generator: tag
16:22:04.459 DEBUG Generator: archive
16:22:04.460 DEBUG Generator: asset
16:22:04.465 INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
16:22:04.473 DEBUG Database saved
16:22:11.053 DEBUG Rendering index: index.html
GET / 200 38.086 ms - -
GET /libs/font-awesome5/css/fontawesome.min.css 200 1.608 ms - -
GET /libs/font-awesome5/css/fa-solid.min.css 200 2.884 ms - -
GET /libs/font-awesome5/css/fa-brands.min.css 200 3.123 ms - -
GET /libs/open-sans/styles.css 200 2.810 ms - -
GET /libs/source-code-pro/styles.css 200 500.449 ms - -
GET /css/style.css 200 500.378 ms - -
GET /libs/jquery/2.1.3/jquery.min.js 200 0.589 ms - -
GET /js/main.js 200 1.305 ms - -
GET /images/mark-cassidy-circle.png 200 1.964 ms - -
GET /images/logo-64x64.png 200 0.496 ms - -
GET /libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSugdm0LZdjqr5-oayXSOefg.woff2 200 1.711 ms - -
GET /libs/open-sans/fonts/cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw.woff2 200 1.139 ms - -
GET /libs/font-awesome5/webfonts/fa-brands-400.woff2 200 1.013 ms - -
GET /libs/font-awesome5/webfonts/fa-solid-900.woff2 200 1.324 ms - -
GET /libs/source-code-pro/fonts/mrl8jkM18OlOQN8JLgasD9V_2ngZ8dMf8fLgjYEouxg.woff2 200 2.997 ms - -
GET /libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBo4P5ICox8Kq3LLUNMylGO4.woff2 200 0.304 ms - -
GET /libs/font-awesome5/css/fa-brands.min.css 200 1.665 ms - -
GET /libs/font-awesome5/css/fontawesome.min.css 200 1.731 ms - -
GET /libs/font-awesome5/css/fa-solid.min.css 200 151.675 ms - -
GET /libs/source-code-pro/styles.css 200 151.372 ms - -
GET /css/style.css 200 151.038 ms - -
GET /libs/open-sans/styles.css 200 154.712 ms - -
```

Site and bug can be observed here: https://intothecloud.blog/

**Comment by demurgos** [comment] 2018-07-16 10:54
Do you encounter this issue only on Chrome or also other browsers? I don't get the issue using Firefox on Windows. I don't even see any `inject.preload.js` file.
It looks like a theme issue, I am not sure if this is related to Hexo.

The server-side logs are irrelevant. Could you instead look at the line causing the error?

**Comment by diguzim** [comment] 2018-07-17 21:10
I got here randomly by searching "inject.preload.js:373" for a problem related to changing dinamically the src field in a html video tag. This issue was reported in Google Chrome, and it doesn't show up in firefox (actually thanks to @demurgos above that I decided to test in firefox).

**Comment by demurgos** [comment] 2018-07-18 08:04
I also tested using Chome on Windows (67.0.3396.99 (64 bits), no extensions). After visiting the website linked above (https://intothecloud.blog/), I still don't get any error.

This is seems to be one of those dreaded Heisenbugs: I can't do anything until I can reproduce it. Could one of you try to build a minimal repro? Or give me your exact browser/OS versions/exact steps?

I am still inclined to think that this is not a Hexo bug. If there is an open issue in a more relevant bug tracker, please link to it. I'd like to close this issue.

**Comment by demurgos** [comment] 2018-07-18 08:10
Closing: this is an Adblock Plus for Chrome issue.

[Adblock issue 6744: An exception thrown from the `inject.preload.js`](https://issues.adblockplus.org/ticket/6744)
(seems fixed, update your plugins)

**Closed by demurgos** 2018-07-18 08:10 UTC
