### ISSUE TITLE
Can windows install Pow？ i tried to run cmd with curl get.pow.cx | sh ，but it doesnt work. 

### ISSUE THREAD

**Issue by qinzeduomoxiong** [hexojs/hexo#3712] opened 2019-09-11 07:03 UTC
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by curbengh** [comment] 2019-09-11 09:01
Duplicate of https://github.com/hexojs/hexo/issues/3711

**Closed by curbengh** 2019-09-11 09:01 UTC
