### ISSUE TITLE
hexo g is truncated by {#

### ISSUE THREAD

**Issue by zh-Closure** [hexojs/hexo#5437] opened 2024-03-17 13:55 UTC
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [ ] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

Displaying the rest of the content normally.

### Actual behavior

When using hexo g to generate static web pages, if there is '{#' in the source file, a truncation issue may occur, and the subsequent content will not be displayed.
<img width="786" alt="{B81BD6E6-9C74-411b-ACC2-0AC623E4127F}" src="https://github.com/hexojs/hexo/assets/86549244/57f851d2-3cf4-41fa-a582-7bc9156e5796">
<img width="687" alt="{7092A4C6-544D-4e73-95A1-5164218B183B}" src="https://github.com/hexojs/hexo/assets/86549244/67878ef6-e136-4beb-96d2-7a3126530f2e">

### How to reproduce?

By writing {#} in the markdown file and triggering hexo g.

### Is the problem still there under `Safe mode`?

I used --safe, but the problem still exists.

### Your Node.js & npm version

```text
> node -v
v18.16.0
> npm -v
9.5.1
```

**Comment by uiolee** [comment] 2024-03-21 02:55
I guess you are using the old version of hexo. 

https://github.com/hexojs/hexo/commit/c1c5aaaf95552f009f9d35a78f0e3b395866e7b8 had make some changes in this problem. In hexo@7.1.1 , if you use the incomplete nunjuck tag `{#}`, nunjuck will throw error.

**Comment by uiolee** [comment] 2024-03-30 13:14
Duplicate of #5301

**Closed by uiolee** 2024-03-30 13:14 UTC
