### ISSUE TITLE
Permalink not including root

### ISSUE THREAD

**Issue by sKawashima** [hexojs/hexo#3601] opened 2019-06-29 01:52 UTC
## Environment Info

This Issue is Continuation of #2610 .
This Issue is Closed, but the BUG is not fixed.

## For BUG

> I've placed <%= page.permalink %> in post.ejs and the result is http://127.0.0.1:4000/El-meu-primer-post-ada5698b/

> This link is not working as root is /blog/. Also <%= config.url + config.root + (page.path||'').replace('index.html', '') %> produces http://127.0.0.1:4000/blog/El-meu-primer-post-ada5698b/ which is ok.

This is very simple BUG, but I think this is IMPORTANT BUG.
Permalink not including root.
Deploy system will use the parameter `url`, `root`, `permalink`.

Now, `post.permalink` not including root : `url` + `permalink`.
It should be `url` + `root` + `permalink`

**Comment by stevenjoezhang** [comment] 2019-09-29 17:31
Duplicate of https://github.com/hexojs/hexo/issues/2105

**Comment by stevenjoezhang** [comment] 2019-09-29 17:36
Both issues can be closed because the current behaviour matches the docs:
```
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
```
In other words, `url` includes `root`. It's not necessary to use `url + root + permalink`

**Closed** 2019-12-20 02:06 UTC
Labels: bug
