### ISSUE TITLE
Add support for pnpm/package.yaml

### ISSUE THREAD

**Issue by sghuang19** [hexojs/hexo#5534] opened 2024-08-13 22:53 UTC
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/).
- [X] I have already searched existing issues.

### Feature Request

Currently only a repo with a `package.json` present can be recognized as a valid Hexo blog repo. i.e. in an unrecognized directory, I need to run `hexo init` first. It would be great to take `package.yaml`, which is used by pnpm into consideration.

**Comment by sghuang19** [comment] 2024-08-13 23:01
Just realized that this is more of a feature request for Hexo-cli. Creating an issue there.

https://github.com/hexojs/hexo-cli/issues/511

**Comment by uiolee** [comment] 2024-10-07 07:56
Duplicate of hexojs/hexo-cli#511

**Closed by uiolee** 2024-10-07 07:56 UTC
