### ISSUE TITLE
The value of `data.slug` in `postPermalinkFilter` is incorrect

### ISSUE THREAD

**Issue by jat001** [hexojs/hexo#4837] opened 2021-12-12 23:48 UTC
I moved some posts from `source/_posts/` to `source/_posts/archive`. And I want to keep the permalink unchanged.
So I changed the config from `permalink: :title.html` to `permalink: :name.html`. But it did not work.

![image](https://user-images.githubusercontent.com/1758850/145734024-1480c9c0-b48a-4402-bbb6-655956ef58b7.png)

It seems the value of `data.slug` is not correct. It should be `archive/mongodb-and-mysql-compared`, not `archive-mongodb-and-mysql-compared`.
Does anyone know where `data.slug` comes from?

**Comment by jat001** [comment] 2021-12-12 23:51
BTW, I am using Windows. Does it work on mac and Linux?

**Comment by jat001** [comment] 2022-02-12 02:13
https://github.com/hexojs/hexo-util/blob/a20e69761cafca7ff02917e79c3307f86a7877b5/lib/slugize.js#L19

so why replace the slash with the hyphen?

https://github.com/hexojs/hexo/blob/860f1bfb77ef8306b7d3a39a4ff8481544a15360/lib/plugins/filter/post_permalink.js#L22

`basename` will not work in this situation.

**Comment by jat001** [comment] 2022-02-12 02:27
BTW, `slug` in `db.json` is generated by `processPost`, which is used in `postPermalinkFilter`.

https://github.com/hexojs/hexo/blob/860f1bfb77ef8306b7d3a39a4ff8481544a15360/lib/plugins/processor/post.js#L99

https://github.com/hexojs/hexo/blob/860f1bfb77ef8306b7d3a39a4ff8481544a15360/lib/plugins/processor/post.js#L94

https://github.com/hexojs/hexo/blob/860f1bfb77ef8306b7d3a39a4ff8481544a15360/lib/plugins/processor/post.js#L213

**Comment by stevenjoezhang** [comment] 2022-11-22 05:33
But, `permalink: :name.html` should work here. `name` will be replaced with filename without dirname and extname.

`basename(slug)` may not match the expected behavior, need to check commit history.

**Comment by stevenjoezhang** [comment] 2022-11-22 05:35
See https://github.com/hexojs/hexo/pull/1247

**Comment by stevenjoezhang** [comment] 2023-07-27 02:26
I will close this Issue because my tests show that using ":name" achieves your expected result. If you find that ":name" is generating incorrect permanent links, please provide the blog source code that can reproduce the issue.

**Closed by stevenjoezhang** 2023-07-27 02:26 UTC
