### ISSUE TITLE
Error: Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by lomo1** [hexojs/hexo#2724] opened 2017-08-22 07:15 UTC
@#

## Environment Info

Node version(`node -v`): v8.2.1

Your site `_config.yml` (Optional): 5.3.0

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
└── ls@0.2.1

## For question
use `hexo` command in terminal today, then i find some error info, but did't influence app use.
The Errors like below:

```bash
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:18:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32) code: 'MODULE_NOT_FOUND' }
```

i tried to `re-uninstall` the hexo-cli and the problem didn't resolve...

**Comment by lomo1** [comment] 2017-08-22 07:22
i use `hexo` for a long time, and it is ok. I find this issue in today, i remembered i installed the npm modules `N` few days ago and ran `sudo n stable`, maybe id influence it ?

**Comment by JLHwung** [comment] 2017-08-22 07:24
Please run
```
cd /usr/local/lib/node_modules/hexo-cli
npm update
```
After that, you can check if this issue can be reproduced.

**Comment by lomo1** [comment] 2017-08-22 07:49
@JLHwung  thanks for your quick response, i tried to do it by your suggestions, but the problem still exists. 
I do `npm update` in the `hexo-cli` folder, but see nothing in terminal...
😣

**Comment by JLHwung** [comment] 2017-08-22 07:52
Could you print the result of
```
npm ls bunyan
``` in the `hexo-cli` folder? Thank you.

**Comment by lomo1** [comment] 2017-08-22 07:55
yeah, of course, `ls` result like below:
```bash
hexo-cli@1.0.3 /usr/local/lib/node_modules/hexo-cli
└─┬ hexo-log@0.1.3
  └── bunyan@1.8.12
```

**Comment by JLHwung** [comment] 2017-08-22 07:59
@lomo1 Thank you. This is not intended and we will mark it as a bug. We will schedule a patch release of `hexo-log`, we recommend you to update `hexo-log` to 0.1.4 after publish.

@NoahDragon Could you publish 0.1.4 version of `hexo-log` so that we could get rid of this kind of error? Thank you.

**Comment by lomo1** [comment] 2017-08-22 08:05
got it, thank u @JLHwung  very much. 🙂

**Comment by NoahDragon** [comment] 2017-08-22 14:33
@JLHwung I publish it to 0.2.0, as the change may break some build, I would like to avoid the auto update via semver.

@lomo1 The 0.2.0 hexo-log has published, please download the latest version and give it a try.

**Comment by JLHwung** [comment] 2017-08-23 01:29
@NoahDragon So we should bump the version of `hexo-cli` as well as `hexo` for the new version of `hexo-log`.

**Comment by JLHwung** [comment] 2017-08-23 01:45
`hexo-cli` and `hexo` have not been updated yet.
Please run
```
cd /usr/local/lib/node_modules/hexo-cli
npm update hexo-log
```

**Comment by lomo1** [comment] 2017-08-23 01:57
i tried this according to your advice, but seems nothing to run and console in terminal and problem still.......

**Comment by JLHwung** [comment] 2017-08-23 02:11
Hi, could you please try
```
cd /usr/local/lib/node_modules/hexo-cli
npm install hexo-log@latest
```
to see if issues can be resolved?

**Comment by lomo1** [comment] 2017-08-23 04:43
thx for your help to fix this problem. 🙂

**Comment by NoahDragon** [comment] 2017-08-23 14:42
@lomo1 If the issue resolved, could you please close this issue?

**Comment by lomo1** [comment] 2017-08-24 01:22
@NoahDragon  ok 👌  🙂

**Closed** 2017-08-24 01:23 UTC
Labels: bug

**Comment by wangleeyom** [comment] 2017-09-26 14:50
I've had the same problem, trying to do what you say, but it doesn't work, so I'm going to try the other way:

```
cd /usr/local/lib/node_modules/hexo-cli/node_modules/_dtrace-provider@0.8.5@dtrace-provider/
```
open `dtrace-provider.js`,and change the file ,comment off part of the code,like that:

```js
// for (var i in builds) {
//     try {
//         var binding = require('./build/' + builds[i] + '/DTraceProviderBindings');
//         DTraceProvider = binding.DTraceProvider;
//         break;
//     } catch (e) {
//         if (err === null) {
//             err = e;
//         }
//     }
// }

if (!DTraceProvider) {
    /*
     * If the platform looks like it _should_ have DTrace
     * available, log a failure to load the bindings.
     */
    if (process.platform === 'darwin' ||
        process.platform === 'sunos' ||
        process.platform === 'freebsd') {
        // console.error(err);
    }

    DTraceProvider = DTraceProviderStub;
}
```
This annoying mistake will go away,I hope I can help you🙂

**Comment by lomo1** [comment] 2017-09-27 06:19
@wangleeyom  mark and thx first. 🙂
